---
########################## dev
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ruleengine?characterEncoding=UTF-8
    username:  root
    password:  123123
    driverClassName: com.mysql.jdbc.Driver
#注册中心端口
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:2111/eureka/