---
########################## dev
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ruleengine?characterEncoding=UTF-8
    username:  root
    password:  123456
    driverClassName: com.mysql.jdbc.Driver
#redis
  redis: 
    host: 192.168.64.128
    port: 6379
    pool:
      max-active: 20
      max-wait: 1
      max-idle: 10
      min-idle: 1
    database: 0
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:2111/eureka/