server:
  port: 8300
#jpa
spring:
  application:
    name: com.cheshangma.ruleengine
  jpa: 
    show-sql: true
    generate-ddl: false
    database: MYSQL
    hibernate: 
      ddl-auto: update
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
  # freemarker
  freemarker: 
    request-context-attribute: request
    allow-request-override: false
    cache: false
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
  #swagger
swagger:
  version: v0.0.9
# 通过zuul代理的url路径目录要写在这里
zuulUrlName: ruleengine

---
########################## test
spring:
  profiles: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.25:3306/ruleengine?characterEncoding=UTF-8
    username:  root
    password:  vd97031
    driverClassName: com.mysql.jdbc.Driver
#redis
  redis: 
    host: 192.168.64.128
    port: 6379
    password: myredis
    pool:
      max-active: 20
      max-wait: 1
      # 空闲时的最大链接数量
      max-idle: 10
      # 空闲时的最小链接数量
      min-idle: 1
    database: 0
#注册中心端口
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://192.168.0.25:2111/eureka/